unit ULibGeral;

interface

uses
  cxLocalization, System.Classes;

type
  TcxLocalizer = class(cxLocalization.TcxLocalizer)
  public
    procedure TraducaoBRDevExpress;
  end;

implementation

{ TcxLocalizer }

procedure TcxLocalizer.TraducaoBRDevExpress;
var
  Lista: TStringList;
  lMemoryStream: TMemoryStream;
begin
  Lista := TStringList.Create;
  Lista.Text :=
  '[1046]' + #13 +
  'cxNavigator_DeleteRecordQuestion="Excluir registro?"' + #13 +
  'cxNavigatorHint_Append="acrescentar registro"' + #13 +
  'cxNavigatorHint_Cancel="Cancelar editar"' + #13 +
  'cxNavigatorHint_Delete="Excluir registro"' + #13 +
  'cxNavigatorHint_Edit="Editar registro"' + #13 +
  'cxNavigatorHint_Filter="Filtrar dados"' + #13 +
  'cxNavigatorHint_First="Primeiro registro"' + #13 +
  'cxNavigatorHint_Insert="Inserir registro"' + #13 +
  'cxNavigatorHint_Last="Último registro"' + #13 +
  'cxNavigatorHint_Next="Próximo registro"' + #13 +
  'cxNavigatorHint_NextPage="Próxima página"' + #13 +
  'cxNavigatorHint_Post="postar editar"' + #13 +
  'cxNavigatorHint_Prior="Antes de gravar"' + #13 +
  'cxNavigatorHint_PriorPage="Antes página"' + #13 +
  'cxNavigatorHint_Refresh="Atualizar dados"' + #13 +
  'cxNavigatorHint_SaveBookmark="Salvar Bookmark"' + #13 +
  'cxSBlobButtonCancel="&Cancelar"' + #13 +
  'cxSBlobButtonClose="&Fechar"' + #13 +
  'cxSBlobPicture="(Figura)"' + #13 +
  'cxSBlobPictureEmpty="(Figura)"' + #13 +
  'cxSCheckComboBoxEmptySelectionText="Nenhum selecionado"' + #13 +
  'cxSCheckComboBoxStatesItemsPropertyDlgCaption="cxCheckComboBox - editor CheckStates"' + #13 +
  'cxSCheckControlIncorrectItemCount="O número de itens não pode ser maior que 64, se o EditValueFormat é cvfInteger"' + #13 +
  'cxSCheckGroupStatesItemsPropertyDlgCaption="cxCheckGroup - editor CheckStates"' + #13 +
  'cxSColorComboBoxDefaultDescription="A cor não selecionado"' + #13 +
  'cxSDataCustomDataSourceInvalidCompare="GetInfoForCompare não implementado"' + #13 +
  'cxSDataInvalidStreamFormat="Stream \n formato Inválido"' + #13 +
  'cxSDataItemExistError="Item já existe"' + #13 +
  'cxSDataItemIndexError="ItemIndex fora do intervalo"' + #13 +
  'cxSDataProviderModeError="Esta operação não é suportado no modo fornecedor"' + #13 +
  'cxSDataReadError="Stream erro de leitura"' + #13 +
  'cxSDataRecordIndexError="RecordIndex fora do intervalo"' + #13 +
  'cxSDataRowIndexError="RowIndex fora do intervalo"' + #13 +
  'cxSDataWriteError="Stream erro de gravação"' + #13 +
  'cxSDateError="Data inválida"' + #13 +
  'cxSDateFifth="quinta"' + #13 +
  'cxSDateFirst="primeiro"' + #13 +
  'cxSDateFourth="quarto"' + #13 +
  'cxSDateFriday="Sexta-feira"' + #13 +
  'cxSDateMonday="Segunda-feira"' + #13 +
  'cxSDateNow="agora"' + #13 +
  'cxSDatePopupClear="Limpar"' + #13 +
  'cxSDatePopupNow="Agora"' + #13 +
  'cxSDatePopupToday="Hoje"' + #13 +
  'cxSDateSaturday="Sábado"' + #13 +
  'cxSDateSecond="segundo"' + #13 +
  'cxSDateSeventh="sétimo"' + #13 +
  'cxSDateSixth="sexto \n"' + #13 +
  'cxSDateSunday="Domingo"' + #13 +
  'cxSDateThird="terceiro"' + #13 +
  'cxSDateThursday="Quinta-feira"' + #13 +
  'cxSDateToday="hoje"' + #13 +
  'cxSDateTomorrow="amanhã"' + #13 +
  'cxSDateTuesday="Terça-feira"' + #13 +
  'cxSDateWednesday="Quarta-feira"' + #13 +
  'cxSDateYesterday="ontem"' + #13 +
  'cxSDBDetailFilterControllerNotFound="DetailFilterController não encontrado"' + #13 +
  'cxSDBKeyFieldNotFound="Key Field não encontrado"' + #13 +
  'cxSDBNotInGridMode="DataController Não está em GridMode"' + #13 +
  'cxSEditButtonCancel="Cancelar"' + #13 +
  'cxSEditCheckBoxChecked="VERDADEIRO"' + #13 +
  'cxSEditCheckBoxUnchecked="Falso"' + #13 +
  'cxSEditCheckGroupChecked="verificado"' + #13 +
  'cxSEditCheckGroupGrayed="Acinzentado"' + #13 +
  'cxSEditCheckGroupUnchecked="Desmarcado"' + #13 +
  'cxSEditDateConvertError="Não foi possível converter a data"' + #13 +
  'cxSEditInvalidRepositoryItem="O item repositório não é aceitável"' + #13 +
  'cxSEditNumericValueConvertError="Não foi possível converter o valor numérico"' + #13 +
  'cxSEditPopupCircularReferencingError="Referenciando Circular não é permitido"' + #13 +
  'cxSEditPostError="Um erro ocorreu durante o lançamento editar o valor"' + #13 +
  'cxSEditRepositoryExtLookupComboBoxItem="ExtLookupComboBox | Representa um ultra-pesquisa avançada usando o QuantumGrid como seu controle drop-down"' + #13 +
  'cxSEditRichEditCallBackFail="RichEdit: Falha ao definir callback"' + #13 +
  'cxSEditRichEditCopyCaption="&copiar"' + #13 +
  'cxSEditRichEditDeleteCaption="&Deletar"' + #13 +
  'cxSEditTimeConvertError="Não foi possível converter a tempo"' + #13 +
  'cxSEditValidateErrorText="Valor de entrada inválido. Use Esc para abandonar as mudanças"' + #13 +
  'cxSEditValueOutOfBounds="Valor fora dos limites"' + #13 +
  'cxSFilterAddCondition="Adicionar &Condições"' + #13 +
  'cxSFilterAddGroup="Adicionar &Grupo"' + #13 +
  'cxSFilterAndCaption="e"' + #13 +
  'cxSFilterBlankCaption="em branco"' + #13 +
  'cxSFilterBoolOperatorAnd="E"' + #13 +
  'cxSFilterBoolOperatorNotAnd="E NÃO"' + #13 +
  'cxSFilterBoolOperatorNotOr="OU NÃO"' + #13 +
  'cxSFilterBoolOperatorOr="OU"' + #13 +
  'cxSFilterBoxAllCaption="(Todos)"' + #13 +
  'cxSFilterBoxBlanksCaption="(Em branco)"' + #13 +
  'cxSFilterBoxCustomCaption="(Personalizar. ..)"' + #13 +
  'cxSFilterBoxNonBlanksCaption="(Preenchido)"' + #13 +
  'cxSFilterClearAll="Limpar &Todos"' + #13 +
  'cxSFilterControlDialogActionApplyCaption="&Aplicar"' + #13 +
  'cxSFilterControlDialogActionCancelCaption="Cancelar"' + #13 +
  'cxSFilterControlDialogActionOpenCaption="&Abrir..."' + #13 +
  'cxSFilterControlDialogActionOpenHint="Abrir | Abre um filtro existente"' + #13 +
  'cxSFilterControlDialogActionSaveCaption="&Salvar Como..."' + #13 +
  'cxSFilterControlDialogActionSaveHint="Salvar como | Salva o filtro ativo com um novo nome"' + #13 +
  'cxSFilterControlDialogCaption="Construtor do Filtro"' + #13 +
  'cxSFilterControlDialogFileFilter="Filtro (*.flt)|*.flt"' + #13 +
  'cxSFilterControlDialogNewFile="SemTitulo.flt"' + #13 +
  'cxSFilterControlDialogOpenDialogCaption="Abrir um filtro existente"' + #13 +
  'cxSFilterControlDialogSaveDialogCaption="Salve o filtro ativo para o arquivo"' + #13 +
  'cxSFilterControlNullString="<Vazio>"' + #13 +
  'cxSFilterDialogCaption="Personalizar Filtro"' + #13 +
  'cxSFilterDialogCharactersSeries="para representar qualquer seqüência de caracteres"' + #13 +
  'cxSFilterDialogInvalidValue="Valor inválido"' + #13 +
  'cxSFilterDialogOperationAnd="E"' + #13 +
  'cxSFilterDialogOperationOr="OU"' + #13 +
  'cxSFilterDialogRows="Mostrar linhas:"' + #13 +
  'cxSFilterDialogSingleCharacter="para representar qualquer caractere único"' + #13 +
  'cxSFilterErrorBuilding="Não é possível criar filtros da fonte"' + #13 +
  'cxSFilterFooterAddCondition="pressione o botão para adicionar uma nova condição"' + #13 +
  'cxSFilterGroupCaption="aplica-se às seguintes condições"' + #13 +
  'cxSFilterNotCaption="não"' + #13 +
  'cxSFilterOperatorBeginsWith="começa com"' + #13 +
  'cxSFilterOperatorBetween="entre"' + #13 +
  'cxSFilterOperatorContains="contém"' + #13 +
  'cxSFilterOperatorDoesNotBeginWith="não começa com"' + #13 +
  'cxSFilterOperatorDoesNotContain="não contém"' + #13 +
  'cxSFilterOperatorDoesNotEndWith="não termina com"' + #13 +
  'cxSFilterOperatorEndsWith="termina com"' + #13 +
  'cxSFilterOperatorEqual="igual"' + #13 +
  'cxSFilterOperatorFuture="é o futuro"' + #13 +
  'cxSFilterOperatorGreater="é maior do que"' + #13 +
  'cxSFilterOperatorGreaterEqual="é maior ou igual a"' + #13 +
  'cxSFilterOperatorInList="em"' + #13 +
  'cxSFilterOperatorIsNotNull="não está em branco"' + #13 +
  'cxSFilterOperatorIsNull="está em branco"' + #13 +
  'cxSFilterOperatorLast14Days="É últimos 14 dias"' + #13 +
  'cxSFilterOperatorLast30Days="É últimos 30 dias"' + #13 +
  'cxSFilterOperatorLast7Days="É últimos 7 dias"' + #13 +
  'cxSFilterOperatorLastMonth="É no mês passado"' + #13 +
  'cxSFilterOperatorLastTwoWeeks="É últimas duas semanas"' + #13 +
  'cxSFilterOperatorLastWeek="É na semana passada"' + #13 +
  'cxSFilterOperatorLastYear="é do ano passado"' + #13 +
  'cxSFilterOperatorLess="é inferior"' + #13 +
  'cxSFilterOperatorLessEqual="é menor ou igual a"' + #13 +
  'cxSFilterOperatorLike="parecido"' + #13 +
  'cxSFilterOperatorNext14Days="é próximos 14 dias"' + #13 +
  'cxSFilterOperatorNext30Days="é próximos 30 dias"' + #13 +
  'cxSFilterOperatorNext7Days="é próximos 7 dias"' + #13 +
  'cxSFilterOperatorNextMonth="é no próximo mês"' + #13 +
  'cxSFilterOperatorNextTwoWeeks="É próximas duas semanas"' + #13 +
  'cxSFilterOperatorNextWeek="é na próxima semana"' + #13 +
  'cxSFilterOperatorNextYear="é no próximo ano"' + #13 +
  'cxSFilterOperatorNotBetween="não entre"' + #13 +
  'cxSFilterOperatorNotEqual="não é igual"' + #13 +
  'cxSFilterOperatorNotInList="Não está em"' + #13 +
  'cxSFilterOperatorNotLike="Não gosto"' + #13 +
  'cxSFilterOperatorPast="é passado"' + #13 +
  'cxSFilterOperatorThisMonth="é este mês"' + #13 +
  'cxSFilterOperatorThisWeek="é esta semana"' + #13 +
  'cxSFilterOperatorThisYear="é este ano"' + #13 +
  'cxSFilterOperatorToday="é hoje"' + #13 +
  'cxSFilterOperatorTomorrow="é amanhã"' + #13 +
  'cxSFilterOperatorYesterday="é tarde"' + #13 +
  'cxSFilterOrCaption="ou"' + #13 +
  'cxSFilterRemoveRow="&Remover Linha"' + #13 +
  'cxSFilterRootButtonCaption="Filtro"' + #13 +
  'cxSFilterRootGroupCaption="<raiz>"' + #13 +
  'cxSGridAlignCenter="Alinhar ao centro"' + #13 +
  'cxSGridAlignLeft="Alinhar à Esquerda"' + #13 +
  'cxSGridAlignmentSubMenu="Alinhamento"' + #13 +
  'cxSGridAlignRight="Alinhar à Direita"' + #13 +
  'cxSGridAvgMenuItem="Média"' + #13 +
  'cxSGridBestFit="Melhor ajuste"' + #13 +
  'cxSGridBestFitAllColumns="Melhor Ajuste (todas as colunas)"' + #13 +
  'cxSGridClearSorting="Limpar Seleção"' + #13 +
  'cxSGridCountMenuItem="Contar"' + #13 +
  'cxSGridFieldChooser="Seletor de Campo"' + #13 +
  'cxSGridGroupByBox="Agrupar por Caixa"' + #13 +
  'cxSGridGroupByThisField="Grupo por este campo"' + #13 +
  'cxSGridNone="Nenhum"' + #13 +
  'cxSGridNoneMenuItem="Nenhum"' + #13 +
  'cxSGridRemoveColumn="Remover esta coluna"' + #13 +
  'cxSGridRemoveThisGroupItem="Retire do agrupamento"' + #13 +
  'cxSGridShowFooter="Rodapé"' + #13 +
  'cxSGridShowGroupFooter="Grupo Rodapés"' + #13 +
  'cxSGridSortByGroupValues="Classificar por grupo Valor"' + #13 +
  'cxSGridSortBySummary="%s para %s"' + #13 +
  'cxSGridSortBySummaryCaption="Ordenar por Grupo Resumo:"' + #13 +
  'cxSGridSortColumnAsc="Ascendente"' + #13 +
  'cxSGridSortColumnDesc="Classificação Decrescente"' + #13 +
  'cxSGridSumMenuItem="Soma"' + #13 +
  'cxSMenuItemCaptionCopy="&Copiar"' + #13 +
  'cxSMenuItemCaptionCut="Cor&tar"' + #13 +
  'cxSMenuItemCaptionDelete="&Deletar"' + #13 +
  'cxSMenuItemCaptionLoad="&Carregar..."' + #13 +
  'cxSMenuItemCaptionPaste="&Colar"' + #13 +
  'cxSMenuItemCaptionSave="Salvar &Como..."' + #13 +
  'cxSSpinEditInvalidNumericValue="Invalid valor numérico"' + #13 +
  'cxSTextFalse="falso"' + #13 +
  'cxSTextTrue="verdadeiro"' + #13 +
  'dxSBAR_ADDEX="Adicionar ..."' + #13 +
  'dxSBAR_ADDGALLERYNAME="Galeria"' + #13 +
  'dxSBAR_ADDREMOVEBUTTONS="&Adicionar ou Remover Botões"' + #13 +
  'dxSBAR_ADDTOQATITEMNAME="&Adiione %s para Quick Acesso \nToolbar"' + #13 +
  'dxSBAR_BARMANAGERBADOWNER="TdxBarManager TWinControl deve ter como seu proprietário"' + #13 +
  'dxSBAR_BARMANAGERMORETHANONE="Um controle deve conter apenas um único TdxBarManager"' + #13 +
  'dxSBAR_BUTTONDEFAULTACTIONDESCRIPTION="apertar"' + #13 +
  'dxSBAR_CANCEL="Cancelar"' + #13 +
  'dxSBAR_CANTASSIGNCONTROL="Você não pode atribuir o mesmo controle para mais de um TdxBarControlContainerItem"' + #13 +
  'dxSBAR_CANTFINDBARMANAGERFORSTATUSBAR="Um gerente de bar não pode ser encontrado para a barra de status"' + #13 +
  'dxSBAR_CANTMERGEBARMANAGER="Você não pode fundir-se com o gerente do bar especificado"' + #13 +
  'dxSBAR_CANTMERGETOOLBAR="Você não pode fundir-se com a barra de ferramentas especificado"' + #13 +
  'dxSBAR_CANTMERGEWITHMERGEDTOOLBAR="Você não pode fundir uma barra de ferramentas com uma barra de ferramentas que já está mesclado"' + #13 +
  'dxSBAR_CANTPLACERIBBONGALLERY="Você pode colocar TdxRibbonGalleryItem apenas na faixa"' + #13 +
  'dxSBAR_CANTPLACESEPARATOR="Um item separador não pode ser colocado na barra de ferramentas especificado"' + #13 +
  'dxSBAR_CANTUNMERGETOOLBAR="Você não pode desinstalar a barra de ferramentas especificado"' + #13 +
  'dxSBAR_CAPTION="Personalizar"' + #13 +
  'dxSBAR_CATEGORIES="Cate&gorias:"' + #13 +
  'dxSBAR_CATEGORYADD="Adicionar Categoria"' + #13 +
  'dxSBAR_CATEGORYINSERT="Inserir Categoria"' + #13 +
  'dxSBAR_CATEGORYNAME="&Nome da Categoria:"' + #13 +
  'dxSBAR_CATEGORYRENAME="Renomear Categoria"' + #13 +
  'dxSBAR_CLEAR="Apagar"' + #13 +
  'dxSBAR_CLEARGALLERYFILTER="Linpar Filtro"' + #13 +
  'dxSBAR_CLOSE="Fechar"' + #13 +
  'dxSBAR_COLOR_STR_0="Preto"' + #13 +
  'dxSBAR_COLOR_STR_1="Marrom"' + #13 +
  'dxSBAR_COLOR_STR_10="Limão"' + #13 +
  'dxSBAR_COLOR_STR_11="Amarelo \n"' + #13 +
  'dxSBAR_COLOR_STR_12="Azul \n"' + #13 +
  'dxSBAR_COLOR_STR_15="Branco \n"' + #13 +
  'dxSBAR_COLOR_STR_2="Verde \n"' + #13 +
  'dxSBAR_COLOR_STR_3="Oliva"' + #13 +
  'dxSBAR_COLOR_STR_4="Marinha \n"' + #13 +
  'dxSBAR_COLOR_STR_5="Púrpura"' + #13 +
  'dxSBAR_COLOR_STR_7="cinza"' + #13 +
  'dxSBAR_COLOR_STR_8="Prata \n"' + #13 +
  'dxSBAR_COLOR_STR_9="Vermelho \n"' + #13 +
  'dxSBAR_COLORAUTOTEXT="(automático \n)"' + #13 +
  'dxSBAR_COLORCUSTOMTEXT="(personalizado)"' + #13 +
  'dxSBAR_COMMANDNAMECANNOTBEBLANK="Um nome de comando não pode ser em branco. Por favor, digite um nome."' + #13 +
  'dxSBAR_COMMANDS="Coman&dos:"' + #13 +
  'dxSBAR_CP_ADDBUTTON="Adicionar&Botão"' + #13 +
  'dxSBAR_CP_ADDCXITEM="Adicionar&cxEditItem"' + #13 +
  'dxSBAR_CP_ADDDXITEM="Adicionar &Item"' + #13 +
  'dxSBAR_CP_ADDGROUPBUTTON="Adicionar Gro&upButton"' + #13 +
  'dxSBAR_CP_ADDLARGEBUTTON="AdicionarL&argeButton"' + #13 +
  'dxSBAR_CP_ADDSEPARATOR="Adicionar&Separator"' + #13 +
  'dxSBAR_CP_ADDSUBITEM="Adicionar&SubItem"' + #13 +
  'dxSBAR_CP_ALLVIEWLEVELS="Todos"' + #13 +
  'dxSBAR_CP_BEGINAGROUP="Começar um &Grupo"' + #13 +
  'dxSBAR_CP_BUTTONGROUP="Grupo"' + #13 +
  'dxSBAR_CP_BUTTONUNGROUP="Desagrupar"' + #13 +
  'dxSBAR_CP_CAPTION="&título:"' + #13 +
  'dxSBAR_CP_DELETE="&Excluir \n"' + #13 +
  'dxSBAR_CP_DELETEITEM="Excluir Item"' + #13 +
  'dxSBAR_CP_DELETELINK="Excluir Link"' + #13 +
  'dxSBAR_CP_DISTRIBUTED="Dis&tribuído"' + #13 +
  'dxSBAR_CP_IMAGEANDTEXT="Imagem &e Texto"' + #13 +
  'dxSBAR_CP_MOSTRECENTLYUSED="&Mais recentemente usado"' + #13 +
  'dxSBAR_CP_NAME="&Nome:"' + #13 +
  'dxSBAR_CP_POSITIONMENU="&Posição"' + #13 +
  'dxSBAR_CP_SINGLEVIEWLEVELITEMSUFFIX="APENAS \n"' + #13 +
  'dxSBAR_CP_TEXTONLYALWAYS="&Somente Texto (sempre)"' + #13 +
  'dxSBAR_CP_TEXTONLYINMENUS="Texto &Only (em Menus)"' + #13 +
  'dxSBAR_CP_VIEWLEVELSMENU="Ver %Níveis"' + #13 +
  'dxSBAR_CP_VISIBLE="&Visível"' + #13 +
  'dxSBAR_CUSTOMIZE="&Personalizar..."' + #13 +
  'dxSBAR_CUSTOMIZINGFORM="Personalização Form..."' + #13 +
  'dxSBAR_CXEDITVALUEDIALOGCAPTION="Digite o valor"' + #13 +
  'dxSBAR_DATECLEAR="Apagar \n"' + #13 +
  'dxSBAR_DATEDIALOGCAPTION="Selecione um dado"' + #13 +
  'dxSBAR_DATETODAY="Hoje \n"' + #13 +
  'dxSBAR_DEFAULTCATEGORYNAME="Padrão"' + #13 +
  'dxSBAR_DELETE="Excluir"' + #13 +
  'dxSBAR_DESCRIPTION="Descrição"' + #13 +
  'dxSBAR_DIALOGCANCEL="Cancelar"' + #13 +
  'dxSBAR_DRAGTOMAKEMENUFLOAT="Arraste para fazer este menu float"' + #13 +
  'dxSBAR_EXPAND="expandir(Ctrl-Down)"' + #13 +
  'dxSBAR_GALLERYEMPTYFILTERCAPTION="<vazio>"' + #13 +
  'dxSBAR_HIDEALLGALLERYGROUPS="Ocultar todos os grupos"' + #13 +
  'dxSBAR_HINTOPT2="Mostrar tecla&s de atalho em descrições"' + #13 +
  'dxSBAR_IMAGEDIALOGCAPTION="Selecionar item"' + #13 +
  'dxSBAR_IMAGEINDEX="Índice de Imagens"' + #13 +
  'dxSBAR_IMAGETEXT="Texo"' + #13 +
  'dxSBAR_INSERTEX="Insira ..."' + #13 +
  'dxSBAR_LARGEICONS="&Ícones Grandes"' + #13 +
  'dxSBAR_LOOKUPDIALOGCANCEL="Cancelar"' + #13 +
  'dxSBAR_LOOKUPDIALOGCAPTION="Valor Selecione"' + #13 +
  'dxSBAR_MDICLOSE="Fechar Janela"' + #13 +
  'dxSBAR_MDIMINIMIZE="Minimizar janela"' + #13 +
  'dxSBAR_MDIRESTORE="Restaurar Janela"' + #13 +
  'dxSBAR_MENUANIM1="(Nenhum)"' + #13 +
  'dxSBAR_MENUANIM2="Aleatório"' + #13 +
  'dxSBAR_MENUANIM3="mostrar"' + #13 +
  'dxSBAR_MENUANIM5="desaparecer"' + #13 +
  'dxSBAR_MENUANIMATIONS="&Menu animados:"' + #13 +
  'dxSBAR_MENUSSHOWRECENTITEMS="Me&nus mostra os comandos recentemente utilizados primeiro"' + #13 +
  'dxSBAR_MINIMIZERIBBON="Mi&nimizar o Ribbon"' + #13 +
  'dxSBAR_MODIFY="... modificar \n"' + #13 +
  'dxSBAR_MOREBUTTONS="Mais Butões"' + #13 +
  'dxSBAR_MORECOMMANDS="&Mais Comandos..."' + #13 +
  'dxSBAR_MOVEDOWN="Descer;"' + #13 +
  'dxSBAR_MOVEUP="Subir;"' + #13 +
  'dxSBAR_NEWBUTTONCAPTION="Novo Botão;"' + #13 +
  'dxSBAR_NEWITEMCAPTION="Novo Item;"' + #13 +
  'dxSBAR_NEWRIBBONGALLERYITEMCAPTION="Nova Galeria;"' + #13 +
  'dxSBAR_NEWSEPARATORCAPTION="Novo Separador;"' + #13 +
  'dxSBAR_NEWSUBITEMCAPTION="Novo SubItem;"' + #13 +
  'dxSBAR_NOBARMANAGERS="Não há TdxBarManagers disponível;"' + #13 +
  'dxSBAR_OK="OK;"' + #13 +
  'dxSBAR_ONEOFTOOLBARSALREADYMERGED="Uma das barras de ferramentas do gerente de bar especificado já está mesclado."' + #13 +
  'dxSBAR_ONEOFTOOLBARSHASMERGEDTOOLBARS="Uma das barras de ferramentas do gerente de bar especificado fundiu barras de ferramentas."' + #13 +
  'dxSBAR_OTHEROPTIONS="Outro ."' + #13 +
  'dxSBAR_PERSMENUSANDTOOLBARS="Menus personalizados e barras de ferramentas.  "' + #13 +
  'dxSBAR_PLACEFORCONTROL="O local para a ."' + #13 +
  'dxSBAR_QUICKACCESSALREADYHASGROUPBUTTON="Barra de Acesso Rápido já contém GroupButton com a mesma barra de ferramentas"' + #13 +
  'dxSBAR_QUICKACCESSGROUPBUTTONTOOLBARNOTDOCKEDINRIBBON="Barra de Ferramentas de Acesso Rápido Grupo Botão não é encaixada na Faixa"' + #13 +
  'dxSBAR_RECURSIVEGROUPS="Você não pode criar grupos recursivos"' + #13 +
  'dxSBAR_RECURSIVEMENUS="Você não pode criar menus recursiva"' + #13 +
  'dxSBAR_REMOVEFROMQAT="&Retire do Quick Access Toolbar"' + #13 +
  'dxSBAR_RENAMEEX="Renomear..."' + #13 +
  'dxSBAR_RESETTOOLBAR="&Redefinir Barra de Ferramentas"' + #13 +
  'dxSBAR_RESETUSAGEDATA="&Redefinir dados de uso"' + #13 +
  'dxSBAR_RIBBONADDEMPTYGROUP="Adicionar Grupo vaziu"' + #13 +
  'dxSBAR_RIBBONADDGROUPWITHTOOLBAR="Adicionar Grupo Com Toolbar"' + #13 +
  'dxSBAR_RIBBONBADOWNER="%s deveria ter como seu TCustomForm Proprietário"' + #13 +
  'dxSBAR_RIBBONBADPARENT="%s TCustomForm deve ter como seu parente"' + #13 +
  'dxSBAR_RIBBONDELETEGROUP="Apagar Grupo"' + #13 +
  'dxSBAR_RIBBONDELETETAB="Excluir Tab"' + #13 +
  'dxSBAR_RIBBONMORETHANONE="Deve haver apenas um %s instância sobre a forma"' + #13 +
  'dxSBAR_SHOWABOVERIBBON="&Show Quick Access Toolbar Acima da Faixa de Opções"' + #13 +
  'dxSBAR_SHOWALLGALLERYGROUPS="Mostrar todos os grupos"' + #13 +
  'dxSBAR_SHOWBELOWRIBBON="&Show Quick Access Toolbar Abaixo do Friso"' + #13 +
  'dxSBAR_SHOWFULLMENUSAFTERDELAY="Mostrar menus completos após um pequeno atraso"' + #13 +
  'dxSBAR_TABSHEET2="Comandos "' + #13 +
  'dxSBAR_TABSHEET3="Opções"' + #13 +
  'dxSBAR_TDELETE="&Excluir"' + #13 +
  'dxSBAR_TNEW="&Novo ..."' + #13 +
  'dxSBAR_TOOLBAREXISTS="Uma barra de ferramentas chamada ''%s'' já existe. Digite outro nome."' + #13 +
  'dxSBAR_TOOLBARHASMERGEDTOOLBARS="O ''%s'' toolbar has merged toolbars"' + #13 +
  'dxSBAR_TOOLBARNEWNAME="personalizar"' + #13 +
  'dxSBAR_TOOLBARRENAME="Renomear \nToolbar"' + #13 +
  'dxSBAR_TOOLBARSALREADYMERGED="O ''%s'' toolbarjá está mesclado com o ''%s'' toolbar"' + #13 +
  'dxSBAR_TOOLBARSARENOTMERGED="O ''%s'' toolbarnão é mesclado com o''%s'' toolbar"' + #13 +
  'dxSBAR_TREEVIEWDIALOGCAPTION="Selecionar item"' + #13 +
  'dxSBAR_TRENAME="R&enomear..."' + #13 +
  'dxSBAR_VISIBLE="Visível"' + #13 +
  'dxSBAR_WANTTOCLEARCOMMANDS="Tem certeza de que deseja excluir todos os comandos no ''%s'' categoria?"' + #13 +
  'dxSBAR_WANTTODELETECATEGORY="Tem certeza de que deseja apagar o ''%s" categoria \n- \ncategoria?"' + #13 +
  'dxSBAR_WANTTODELETECOMPLEXITEM="Um dos objetos selecionados é um item que tem vários links. Tem certeza de que deseja excluir estes links?"' + #13 +
  'dxSBAR_WANTTODELETETOOLBAR="Tem certeza de que deseja apagar o "%s" toolbar?"' + #13 +
  'dxSBAR_WANTTODELETETOOLBARS="Tem certeza que pretende eliminar as barras de ferramentas selecionadas?"' + #13 +
  'dxSBAR_WANTTORESETTOOLBAR="Tem certeza que pretende repor as alterações efectuadas ao"%s" toolbar?"' + #13 +
  'dxSBAR_WANTTORESETUSAGEDATA="Isto irá apagar o registro dos comandos usados neste aplicativo e restaurar o conjunto ' +#13+
  'predefinido de comandos visíveis para os menus e barras de ferramentas. Ele não irá desfazer todas as personalizações explícito. ' +#13+
  'Tem certeza de que deseja prosseguir?"' + #13 +
  'scxActualFinishField="Concluir real"' + #13 +
  'scxActualStartField="Início real"' + #13 +
  'scxAdd="&Adiciona"' + #13 +
  'scxAdd1="Adiciona"' + #13 +
  'scxAddedHolidaysGroupBox="Adicionar Feriados"' + #13 +
  'scxAdvance0h="0 horas antes de Iniciar"' + #13 +
  'scxAdvance10m="10 minutos antes de Iniciar"' + #13 +
  'scxAdvance15m="15 minutos antes de Iniciar"' + #13 +
  'scxAdvance5m="5 minutos antes de Iniciar"' + #13 +
  'scxAllDayEvent="&Todo Evento do Dia"' + #13 +
  'scxAllDayEventField="Todo Evento do Dia"' + #13 +
  'scxApply="&Aplicar"' + #13 +
  'scxBoolTrue="verdadeiro"' + #13 +
  'scxBusy="Ocupado"' + #13 +
  'scxCancel="&Cancelar"' + #13 +
  'scxCantCreateExportOutputFile="Não foi possível criar o arquivo de saída de exportação"' + #13 +
  'scxCantCreateRegistryKey="Não é Possível Criar uma chave de registro: \%s"' + #13 +
  'scxCantOpenRegistryKey="Não é possível abrir a chave de registro: \%s"' + #13 +
  'scxCaptionField="Legenda"' + #13 +
  'scxClose="&Fechar"' + #13 +
  'scxComplete="Completo"' + #13 +
  'scxConfirmLostExceptions="Todas as exceções associadas a este evento recorrente será perdido, Confirma?"' + #13 +
  'scxConverterCantCreateStyleRepository="Não é possível criar o repositório Estilo"' + #13 +
  'scxCustom="Personalizar Ocorrência"' + #13 +
  'scxDaily="&Diariamente \n"' + #13 +
  'scxDate="&Data:"' + #13 +
  'scxDay="Dia"' + #13 +
  'scxDay1="dia"' + #13 +
  'scxDayCalendar="Dia do calendário"' + #13 +
  'scxDays="dia(s)"' + #13 +
  'scxDeferred="Adiado"' + #13 +
  'scxDelete="&Apagar"' + #13 +
  'scxDelete1="Apagar"' + #13 +
  'scxDeleteConfirmation="Este item foi alterado. Você tem certeza que deseja apagá-lo?"' + #13 +
  'scxDeleteRecurringEventDescription="é um evento recorrente. Você quer excluir somente esta ocorrência ou a série?"' + #13 +
  'scxDeleteTypeDialogCaption="Confirma a Exclusao"' + #13 +
  'scxDeleteTypeOccurrenceLabel="Excluir esta ocorrência"' + #13 +
  'scxDeleteTypeSeriesLabel="Excluir a série"' + #13 +
  'scxDown="&Abaixar"' + #13 +
  'scxDuration="Duração:"' + #13 +
  'scxEdit="&Editar"' + #13 +
  'scxEdit1="Editar"' + #13 +
  'scxEditRecurringEventDescription="é um evento recorrente. Você quer abrir somente esta ocorrência ou a série?"' + #13 +
  'scxEditTypeDialogCaption="Abrir Item Periódico"' + #13 +
  'scxEditTypeOccurrenceLabel="Abrir esta ocorrência"' + #13 +
  'scxEditTypeSeriesLabel="Abrir a série"' + #13 +
  'scxEmptyExportCache="Exportação cache está vazio"' + #13 +
  'scxEnabledField="Habilitado"' + #13 +
  'scxEnd="&Fim:"' + #13 +
  'scxEndAfter="após o Fim:"' + #13 +
  'scxEndBy="Terminado por:"' + #13 +
  'scxEndTime="&Fim do Tempo:"' + #13 +
  'scxErrorStoreObject="Erro loja%s objeto"' + #13 +
  'scxEvent="Evento"' + #13 +
  'scxEventLabel0="Importante"' + #13 +
  'scxEventLabel1="Negócio"' + #13 +
  'scxEventLabel2="Pessoal"' + #13 +
  'scxEventLabel3="Férias"' + #13 +
  'scxEventLabel4="Deve Comparecer"' + #13 +
  'scxEventLabel5="Viagem Necessária"' + #13 +
  'scxEventLabel6="Necessidades de preparação"' + #13 +
  'scxEventLabel7="Aniversário"' + #13 +
  'scxEventLabel8="Folga"' + #13 +
  'scxEventLabel9="Telefone"' + #13 +
  'scxEventLabelNone="Nenhum "' + #13 +
  'scxEventsConflict="Conflitos com outro evento em sua programação."' + #13 +
  'scxEventTime=" Tempo do Evento"' + #13 +
  'scxEventTypeField="Tipo \n"' + #13 +
  'scxEvery="Cada"' + #13 +
  'scxEveryWeekDay="Cada dia da semana"' + #13 +
  'scxException="Ocorrência de exceção"' + #13 +
  'scxExceptionEvent="evento de exceção"' + #13 +
  'scxExitConfirmation="Deseja salvar as alterações??"' + #13 +
  'scxExport="&Exporta \n"' + #13 +
  'scxExportToExcel="Exportar paraMS Excel (*.xls)"' + #13 +
  'scxExportToHtml="Exportar para a página da Web (*.html)"' + #13 +
  'scxExportToText="Exportar para o formato de texto(*.txt)"' + #13 +
  'scxExportToXml="Exportar para o documento XML(*.xml)"' + #13 +
  'scxFindAvailableTime="Encontre tempo disponível"' + #13 +
  'scxFinishField="Concluir"' + #13 +
  'scxFinishToFinish="Concluir-para-Terminar"' + #13 +
  'scxFinishToFinishLong="Concluir-para-terminar (FF)"' + #13 +
  'scxFinishToStart="Concluir-para-Iniciar"' + #13 +
  'scxFinishToStartLong="Concluir-para-Iniciar (FS)"' + #13 +
  'scxFirst="Primeiro"' + #13 +
  'scxFirstButtonHint="Primeiro recurso"' + #13 +
  'scxFourth="quarta"' + #13 +
  'scxFree="Livre"' + #13 +
  'scxFrom="De:"' + #13 +
  'scxFullYear="O Ano  \nInteiro"' + #13 +
  'scxGanttEventHint="Terefa: %s \nCompleto: %d %% \nInicio: %s \nAcabamento: %s"' + #13 +
  'scxGoToDateDialogCaption="Ir para data"' + #13 +
  'scxGridBandsQuickCustomizationHint="Clique aqui para exibir / ocultar / bandas mover"' + #13 +
  'scxGridChartAlignment="Alinhamento"' + #13 +
  'scxGridChartAlignmentCenter="Centro"' + #13 +
  'scxGridChartAlignmentDefault="Padrão"' + #13 +
  'scxGridChartAlignmentEnd="Fim"' + #13 +
  'scxGridChartAlignmentStart="Iniciar"' + #13 +
  'scxGridChartAreaDiagramDisplayText="Diagrama de Área"' + #13 +
  'scxGridChartBarDiagramDisplayText="Diagrama de barras"' + #13 +
  'scxGridChartBorder="Borda"' + #13 +
  'scxGridChartCategoriesDisplayText="Dados"' + #13 +
  'scxGridChartColumnDiagramDisplayText="Diagrama de Coluna"' + #13 +
  'scxGridChartCustomizationFormDataGroupsPageCaption="Grupos de Dados"' + #13 +
  'scxGridChartCustomizationFormNoSortedSeries="<nenhuma série>"' + #13 +
  'scxGridChartCustomizationFormOptionsPageCaption="Opções"' + #13 +
  'scxGridChartCustomizationFormSeriesPageCaption="Série"' + #13 +
  'scxGridChartCustomizationFormSortBySeries="Ordenar por:"' + #13 +
  'scxGridChartDiagramSelector="Diagrama Selector"' + #13 +
  'scxGridChartLegend="Legenda"' + #13 +
  'scxGridChartLineDiagramDisplayText="Diagrama Line"' + #13 +
  'scxGridChartNoneDiagramDisplayText="No diagrama"' + #13 +
  'scxGridChartOrientation="Orientação"' + #13 +
  'scxGridChartOrientationDefault="Padrão"' + #13 +
  'scxGridChartOther="Outro"' + #13 +
  'scxGridChartPieDiagramDisplayText="Diagrama Pie"' + #13 +
  'scxGridChartPosition="Posição"' + #13 +
  'scxGridChartPositionBottom="Fundo"' + #13 +
  'scxGridChartPositionDefault="Padrão"' + #13 +
  'scxGridChartPositionLeft="Esquerdo"' + #13 +
  'scxGridChartPositionNone="Nenhum"' + #13 +
  'scxGridChartPositionRight="Direito"' + #13 +
  'scxGridChartPositionTop="Topo"' + #13 +
  'scxGridChartTitle="Título"' + #13 +
  'scxGridChartToolBoxCustomizeButtonCaption="Customize Gráfico"' + #13 +
  'scxGridChartToolBoxDataLevels="Dados dos níveis:"' + #13 +
  'scxGridChartToolBoxDataLevelSelectValue="Selecione valor"' + #13 +
  'scxGridChartValueHintFormat="%s para %s é %s"' + #13 +
  'scxGridChartValueHints="Valor Dicas"' + #13 +
  'scxGridColumnsQuickCustomizationHint="Clique aqui para mostrar / esconder / mover colunas"' + #13 +
  'scxGridConverterIntermediaryMissing="Faltando um componente intermediário! \nPor favor, adicione uma %s componente para o formulário."' + #13 +
  'scxGridConverterNotExistComponent="Componente não existe"' + #13 +
  'scxGridConverterNotExistGrid="cxGridnão existe"' + #13 +
  'scxGridCustomizationFormBandsPageCaption="Bandas"' + #13 +
  'scxGridCustomizationFormCaption="Personalização"' + #13 +
  'scxGridCustomizationFormColumnsPageCaption="Colunas"' + #13 +
  'scxGridCustomizationFormRowsPageCaption="Filas"' + #13 +
  'scxGridDeletingConfirmationCaption="Confirme"' + #13 +
  'scxGridDeletingFocusedConfirmationText="Deletar registro?"' + #13 +
  'scxGridDeletingSelectedConfirmationText="Excluir todos os registros selecionados?"' + #13 +
  'scxGridFilterApplyButtonCaption="Aplicar filtro"' + #13 +
  'scxGridFilterCustomizeButtonCaption="Personalizar ..."' + #13 +
  'scxGridFilterIsEmpty="<Filtro está vazio>"' + #13 +
  'scxGridFilterRowInfoText="Clique aqui para definir um filtro"' + #13 +
  'scxGridFuture="Futuro"' + #13 +
  'scxGridGroupByBoxCaption="Arraste um cabeçalho da coluna aqui para agrupar por essa coluna"' + #13 +
  'scxGridLast14Days="Últimos 14 dias"' + #13 +
  'scxGridLast30Days="Últimos 30 dias"' + #13 +
  'scxGridLast7Days="Últimos 7 dias"' + #13 +
  'scxGridLastMonth="mês passado"' + #13 +
  'scxGridLastTwoWeeks="Últimas duas semanas"' + #13 +
  'scxGridLastWeek="semana passada"' + #13 +
  'scxGridLastYear="ano passado"' + #13 +
  'scxGridNewItemRowInfoText="Clique aqui para adicionar uma nova linha"' + #13 +
  'scxGridNext14Days="Próximos 14 dias"' + #13 +
  'scxGridNext30Days="Próximos 30 dias"' + #13 +
  'scxGridNext7Days="Próximos 7 dias"' + #13 +
  'scxGridNextMonth="Próximo mês \n- \npróximo mês"' + #13 +
  'scxGridNextTwoWeeks="Próximas duas semanas"' + #13 +
  'scxGridNextWeek="Próxima semana \n"' + #13 +
  'scxGridNextYear="ano seguinte"' + #13 +
  'scxGridNoDataInfoText="<Não há dados para mostrar>"' + #13 +
  'scxGridPast="Passado"' + #13 +
  'scxGridRecursiveLevels="Você não pode criar níveis recursivos"' + #13 +
  'scxGridThisMonth="Este mês"' + #13 +
  'scxGridThisWeek="Esta semana"' + #13 +
  'scxGridThisYear="Este ano"' + #13 +
  'scxGridToday="Hoje"' + #13 +
  'scxGridTomorrow="Amanhã"' + #13 +
  'scxGridYesterday="Ontem"' + #13 +
  'scxHalfYear="Semestre"' + #13 +
  'scxHolidayDate="Data:"' + #13 +
  'scxHolidayName="Nome:"' + #13 +
  'scxHolidaysEditorCaption="Editor Feriados"' + #13 +
  'scxHolidaysGroupBox="Feriados"' + #13 +
  'scxHolidaysLocationEditorCaption="Editor Local"' + #13 +
  'scxHolidaysLocationHolidayEditorCaption="Editor de feriado"' + #13 +
  'scxHour="Hora"' + #13 +
  'scxHours="Horas"' + #13 +
  'scxIllegalHeight="Illegal altura da linha"' + #13 +
  'scxIllegalWidth="Illegal largura da coluna"' + #13 +
  'scxImport="&Importação "' + #13 +
  'scxImportErrorCaption="Erro de Importação"' + #13 +
  'scxIncorrectUnion="União incorreta de pilhas"' + #13 +
  'scxInProgress="Em Desenvolvimento"' + #13 +
  'scxInvalidCellDimension="Invalid dimensão de células"' + #13 +
  'scxInvalidColumnIndex="O índice de coluna %d fora dos limites"' + #13 +
  'scxInvalidColumnRowCount="Contagem de coluna inválido ou linha"' + #13 +
  'scxInvalidCustomField="Inválido campo personalizado"' + #13 +
  'scxInvalidFieldName="Nome do Campo Inválido"' + #13 +
  'scxInvalidNumber="Você deve digitar um número válido."' + #13 +
  'scxInvalidRecurrenceDuration="A duração do evento deve ser menor do que a freqüência com que ocorre. Encurtar a duração, ou mudar o padrão de recorrência na caixa de diálogo Recorrência."' + #13 +
  'scxInvalidRowIndex="O índice da linha %d fora dos limites"' + #13 +
  'scxInvalidStyleIndex="Inválido índice %d estilo"' + #13 +
  'scxLabel="Rótulo:"' + #13 +
  'scxLabelField="Rótulo"' + #13 +
  'scxLast="Último"' + #13 +
  'scxLastButtonHint="Último Recurso"' + #13 +
  'scxLinkHint="Tarefa Link: %s (%s) \nPara: %s \nde: %s"' + #13 +
  'scxLocation="&Local:"' + #13 +
  'scxLocationField="Local"' + #13 +
  'scxLocationName="Nome:"' + #13 +
  'scxLocationsGroupBox="Locais"' + #13 +
  'scxMaskEditEmptyMaskCollectionFile="O arquivo de máscara coleção está vazia"' + #13 +
  'scxMaskEditIllegalFileFormat="Ilegal formato de arquivo"' + #13 +
  'scxMaskEditInvalidEditValue="A editar o valor é inválido"' + #13 +
  'scxMaskEditMaskCollectionFiles="Coleção de arquivos Máscara"' + #13 +
  'scxMaskEditNoMask="Nenhum"' + #13 +
  'scxMaskEditRegExprError="Regular erros de expressão"' + #13 +
  'scxMessageField="Mensagem"' + #13 +
  'scxMinute="Minuto"' + #13 +
  'scxMinutes="Minutos"' + #13 +
  'scxMonthCalendar="Mês do calendário"' + #13 +
  'scxMonthly="&Mensal"' + #13 +
  'scxMonths="Meses"' + #13 +
  'scxNextAppointment="Próximo compromisso"' + #13 +
  'scxNextButtonHint="Próximo Recurso"' + #13 +
  'scxNextPageButtonHint="Próxima Página"' + #13 +
  'scxNoAvailableFreeTime="Sem há tempo livre disponível."' + #13 +
  'scxNoEndDate="&Sem data final"' + #13 +
  'scxNone="Evento Simples"' + #13 +
  'scxNoneEvent="eventos simples"' + #13 +
  'scxNotExistGridLevel="Nível de rede Active não existe"' + #13 +
  'scxNotExistGridView="Grid view não existe"' + #13 +
  'scxNotStarted="Não Iniciado"' + #13 +
  'scxOccurenceEvent="ocorrência de eventos"' + #13 +
  'scxOccurences="ocorrências"' + #13 +
  'scxOccurrence="Ocorrência Simples"' + #13 +
  'scxOf="de"' + #13 +
  'scxOfEvery="de cada"' + #13 +
  'scxOneDay="Um Dia"' + #13 +
  'scxOutlookFormatMismatch="Férias incompatibilidade de formatos"' + #13 +
  'scxOutOfOffice="Fora do escritório"' + #13 +
  'scxPattern="Padrão de Recorrência"' + #13 +
  'scxpm10Minutes="10 &Minuto"' + #13 +
  'scxpm15Minutes="&15 Minuto"' + #13 +
  'scxpm30Minutes="&30 Minuto"' + #13 +
  'scxpm5Minutes="&5 Minuto"' + #13 +
  'scxpm60Minutes="6&0 Minuto"' + #13 +
  'scxpm6Minutes="&6 Minuto"' + #13 +
  'scxpmBusy="&Ocupado"' + #13 +
  'scxpmDelete="&Excluir"' + #13 +
  'scxpmEditSeries="Editar Série"' + #13 +
  'scxpmFree="&Livre"' + #13 +
  'scxpmFullYear="&Ano Inteiro"' + #13 +
  'scxpmGoToDate="Ir para Data..."' + #13 +
  'scxpmGotoThisDay="Ir para o Dia"' + #13 +
  'scxpmHalfYear="&Meio-do-no"' + #13 +
  'scxpmLabel="&Rótulo"' + #13 +
  'scxpmNewAllDayEvent="Evento o Dia Todo"' + #13 +
  'scxpmNewEvent="&Novo Evento"' + #13 +
  'scxpmNewRecurringEvent="Novo Evento Recorrente"' + #13 +
  'scxpmOpen="&Abrir"' + #13 +
  'scxpmOutOfOffice="&Fora do Escritório"' + #13 +
  'scxpmQuarter="&Trimestre"' + #13 +
  'scxpmResourcesLayout="editor de Recurso..."' + #13 +
  'scxpmShowTimeAs="Mostrar hora"' + #13 +
  'scxpmTentative="&Tentativa"' + #13 +
  'scxpmTimeZone=" Mudança de fuso horário"' + #13 +
  'scxpmToday="Hoje"' + #13 +
  'scxPrevAppointment="Compromisso Anterior"' + #13 +
  'scxPrevButtonHint="Recursos anterior"' + #13 +
  'scxPrevPageButtonHint="Página Anterior"' + #13 +
  'scxQuarter="Trimestre"' + #13 +
  'scxQuarterly="&Trimestrais"' + #13 +
  'scxQuarterShort="T"' + #13 +
  'scxRangeOfRecurrence=" Intervalo de recorrência"' + #13 +
  'scxrCaptionReminder="1 Lembrente"' + #13 +
  'scxrCaptionReminders="%d Lembretes"' + #13 +
  'scxrDismissAllButton="Descartar &Tudo"' + #13 +
  'scxrDismissButton="&Demitir"' + #13 +
  'scxrDueIn="Devido, em"' + #13 +
  'scxRecurEvery="Repetir a cada"' + #13 +
  'scxRecurrence="&Recorrência"' + #13 +
  'scxRecurrenceCaption="recorrência de eventos"' + #13 +
  'scxRecurrenceDailyMessage="Diariamente"' + #13 +
  'scxRecurrenceEvent="caso de recidiva"' + #13 +
  'scxRecurrenceField="Padrão de Recorrência"' + #13 +
  'scxRecurrenceIndexField="Índice de recorrência"' + #13 +
  'scxRecurrenceLabel="Recorrência:"' + #13 +
  'scxRecurrenceMonthlyMessage="Mensal"' + #13 +
  'scxRecurrencePattern=" Padrão de recorrência"' + #13 +
  'scxRecurrenceWeeklyMessage="Semanal"' + #13 +
  'scxRecurrenceYearlyMessage="Anualmente"' + #13 +
  'scxRegExprCantCreateEmptyAlt="A alternativa não deve estar vazia"' + #13 +
  'scxRegExprCantCreateEmptyBlock="O bloco não deve ser vazio"' + #13 +
  'scxRegExprCantCreateEmptyEnum="Não é possível criar enumeração vazio"' + #13 +
  'scxRegExprCantUseParameterQuantifier="O parâmetro quantificador não pode ser aplicado aqui"' + #13 +
  'scxRegExprCantUsePlusQuantifier="O "+" quantificador não pode ser aplicado aqui"' + #13 +
  'scxRegExprCantUseStarQuantifier="O "*" quantificador não pode ser aplicado aqui"' + #13 +
  'scxRegExprEmptySourceStream="O fluxo de origem está vazio"' + #13 +
  'scxRegExprHexNumberExpected="Número hexadecimal esperado, mas "% s" encontrado"' + #13 +
  'scxRegExprHexNumberExpected0="Número hexadecimal esperado"' + #13 +
  'scxRegExprIllegalIntegerValue="Illegal valor inteiro"' + #13 +
  'scxRegExprIllegalQuantifier="% Illegal quantificador "s""' + #13 +
  'scxRegExprIllegalSymbol="Ilegal "%s""' + #13 +
  'scxRegExprIncorrectParameterQuantifier="Parâmetro quantificador incorreta"' + #13 +
  'scxRegExprIncorrectSpace="O carácter de espaço não é permitido após "\""' + #13 +
  'scxRegExprLine="linha"' + #13 +
  'scxRegExprMissing="perdido "%s""' + #13 +
  'scxRegExprNotAssignedSourceStream="O fluxo de origem não é atribuído"' + #13 +
  'scxRegExprNotCompiled="A expressão regular não é compilado"' + #13 +
  'scxRegExprNotSupportQuantifier="Os quantificadores parâmetro não são suportados"' + #13 +
  'scxRegExprSubrangeOrder="O personagem a partir do subrange deve ser inferior a um acabamento"' + #13 +
  'scxRegExprTooBigReferenceNumber="Demasiado grande número de referência"' + #13 +
  'scxRegExprUnnecessary="desnecessário "%s""' + #13 +
  'scxReminder="Lembrete:"' + #13 +
  'scxReminderDateField="LembreteData"' + #13 +
  'scxReminderField="Lembrete"' + #13 +
  'scxReminderMinutesBeforeStartField="Lembre-me minutos antes de iniciar"' + #13 +
  'scxRemoveRecur="&Remover recorrência"' + #13 +
  'scxReplaceOccurrenceDate="Alguns meses têm menos dias s%. Por estes meses, a ocorrência cairão no último dia do mês."' + #13 +
  'scxRequiredFieldsNeeded="Os seguintes campos obrigatórios \n% Não sare atribuído!"' + #13 +
  'scxResource="Recursos"' + #13 +
  'scxResourceField="Recursos"' + #13 +
  'scxResourceLayoutCaption="Editor de Recursos"' + #13 +
  'scxrOpenItemButton="&Abrir Item"' + #13 +
  'scxrSelected="%d lembretes selecionados"' + #13 +
  'scxrSnoozeButton="&Soneca"' + #13 +
  'scxrSnoozeLabel="&Soneca"' + #13 +
  'scxrStartTime="Hora de início: %s"' + #13 +
  'scxrSubject="Assunto"' + #13 +
  'scxSCalcError="erro"' + #13 +
  'scxSecond="segunda"' + #13 +
  'scxSEditRepositoryBlobItem="BlobEdit | representa o editor BLOB"' + #13 +
  'scxSEditRepositoryButtonItem="ButtonEdit | Representa um controle editar com botões embutidos"' + #13 +
  'scxSEditRepositoryCalcItem="CalcEdit | Representa um controle de edição com uma janela da calculadora suspensa"' + #13 +
  'scxSEditRepositoryCheckBoxItem="CheckBox | Representa um controle caixa de seleção que permite selecionar uma opção"' + #13 +
  'scxSEditRepositoryComboBoxItem="ComboBox | Representa o editor de caixa de combinação"' + #13 +
  'scxSEditRepositoryCurrencyItem="CurrencyEdit | Representa um editor que permite a edição de dados de moeda"' + #13 +
  'scxSEditRepositoryDateItem="DateEdit | Representa um controle de edição com um calendário suspenso"' + #13 +
  'scxSEditRepositoryHyperLinkItem="HyperLink | Representa um editor de texto com hiperlink funcionalidade"' + #13 +
  'scxSEditRepositoryImageComboBoxItem="ImageComboBox | Representa um editor de apresentação da lista de imagens e seqüências de texto dentro da janela suspensa"' + #13 +
  'scxSEditRepositoryImageItem="Imagem | Representa um editor de imagem"' + #13 +
  'scxSEditRepositoryLookupComboBoxItem="LookupComboBox | Representa um controle caixa de combinação de pesquisa"' + #13 +
  'scxSEditRepositoryMaskItem="MaskEdit | Representa um genérico mascarado editar o controle."' + #13 +
  'scxSEditRepositoryMemoItem="Memo | Representa um controle de edição que permite que dados memorando de edição"' + #13 +
  'scxSEditRepositoryMRUItem="MRUEdit | Representa um editor de texto de apresentação da lista de itens utilizados mais recentemente (MRU) dentro de uma janela suspensa"' + #13 +
  'scxSEditRepositoryPopupItem="PopupEdit | Representa um controle de edição com uma lista suspensa"' + #13 +
  'scxSEditRepositoryRadioGroupItem="RadioGroup | Representa um grupo de botões de rádio"' + #13 +
  'scxSEditRepositorySpinItem="SpinEdit | Representa um editor de spin"' + #13 +
  'scxSEditRepositoryTextItem="TextEdit | Representa um editor de texto de linha única"' + #13 +
  'scxSEditRepositoryTimeItem="TimeEdit | Representa um editor exibindo valores de tempo"' + #13 +
  'scxSelectAll="Selecionar todos"' + #13 +
  'scxSelectNone="Selecionar nenhum"' + #13 +
  'scxShowFewerResourcesButtonHint="Mostre Menos Recurso"' + #13 +
  'scxShowIn="&Mostrar em:"' + #13 +
  'scxShowMoreResourcesButtonHint="Mostre Mais Recursos"' + #13 +
  'scxShowTimeAs="Mostrar horário como:"' + #13 +
  'scxStart="Inicio:"' + #13 +
  'scxStart1="Inicio:"' + #13 +
  'scxStartField="Inicio"' + #13 +
  'scxStartTime="Hora de início:"' + #13 +
  'scxStartToFinish="Iniciar-para-Concluir"' + #13 +
  'scxStartToFinishLong="Iniciar-para-concluir (SF)"' + #13 +
  'scxStateField="Estado"' + #13 +
  'scxStyleManagerCreate="Não é possível criar gerente de estilo"' + #13 +
  'scxStyleManagerKill="O Gerente de estilo está sendo usado em outro lugar e não pode ser liberada nesta fase"' + #13 +
  'scxSubject="&Assunto:"' + #13 +
  'scxSuffixDay="dia"' + #13 +
  'scxSuffixDays="Dias \n"' + #13 +
  'scxSuffixHour="hora"' + #13 +
  'scxSuffixHours="Horas"' + #13 +
  'scxSuffixMinute="minuto"' + #13 +
  'scxSuffixMinutes="minutos"' + #13 +
  'scxSuffixWeek="semana"' + #13 +
  'scxSuffixWeeks="semanas"' + #13 +
  'scxTaskComplete="Tarefa Completa:"' + #13 +
  'scxTaskCompleteField="Tarefe Completa"' + #13 +
  'scxTaskDependencyEditorCaption="Tarefa Pendente"' + #13 +
  'scxTaskIndexField="Indice da Tarefa"' + #13 +
  'scxTaskLinksField="Tarefe Links"' + #13 +
  'scxTaskStatus="Estado da Tarefa"' + #13 +
  'scxTaskStatusField="Estado da Tarefa"' + #13 +
  'scxTaskWrongTimeBounds="Uma nova data deve ser inserida dentro do período de % s -% s."' + #13 +
  'scxTentative="Tentativa"' + #13 +
  'scxThe="A"' + #13 +
  'scxThird="terceiro"' + #13 +
  'scxTime0m="0 minuto"' + #13 +
  'scxTime10h="10 horas"' + #13 +
  'scxTime10m="10 minutos"' + #13 +
  'scxTime11h="11 horas"' + #13 +
  'scxTime12h="12 horas"' + #13 +
  'scxTime15m="15 minutos"' + #13 +
  'scxTime18h="18 horas"' + #13 +
  'scxTime1d="1 dia"' + #13 +
  'scxTime1h="1 horas"' + #13 +
  'scxTime1w="1 semana"' + #13 +
  'scxTime20m="20 minutos"' + #13 +
  'scxTime2d="2 dia"' + #13 +
  'scxTime2h="2 horas"' + #13 +
  'scxTime2w="2 semanas"' + #13 +
  'scxTime30m="30 minutos"' + #13 +
  'scxTime3d="3 dia"' + #13 +
  'scxTime3h="3 horas"' + #13 +
  'scxTime4d="4 dia"' + #13 +
  'scxTime4h="4 horas"' + #13 +
  'scxTime5h="5 horas"' + #13 +
  'scxTime5m="5 minutos"' + #13 +
  'scxTime6h="6 horas"' + #13 +
  'scxTime7h="7 horas"' + #13 +
  'scxTime8h="8 horas"' + #13 +
  'scxTime9h="9 horas"' + #13 +
  'scxTo="Para:"' + #13 +
  'scxType="&Tipo:"' + #13 +
  'scxUnsupportedExport="Tipo exportação não suportada: %1"' + #13 +
  'scxUntitled="Sem Título"' + #13 +
  'scxUntitledEvent="Sem Evento"' + #13 +
  'scxUp="&Pra Cima"' + #13 +
  'scxWaiting="Esperando"' + #13 +
  'scxWeekCalendar="Calendário da semana"' + #13 +
  'scxWeekday="Semana"' + #13 +
  'scxWeekendday="Dia da Semana \n"' + #13 +
  'scxWeekly="&Semanal"' + #13 +
  'scxWeeksOn="Semana(s) Em:"' + #13 +
  'scxWorkbookWrite="Erro ao gravar arquivo XLS"' + #13 +
  'scxWorkWeekCalendar="Trabalho Agenda da Semana"' + #13 +
  'scxWrongPattern="O padrão de recorrência não é válido."' + #13 +
  'scxWrongTimeBounds="A data final que você inseriu ocorre antes da data de início."' + #13 +
  'scxYearly="&Anualmente"' + #13 +
  'sdx3DEffects="Efeitos 3D"' + #13 +
  'sdx760V12Transmission="Elec 6-velocidades automática w / Steptronic"' + #13 +
  'sdxAbortPrinting="Abortar impressão?"' + #13 +
  'sdxAddAndDesignReport="Adicionar e D&esign Report..."' + #13 +
  'sdxAddItemsToComposition="Adicionar Itens ao Composição"' + #13 +
  'sdxAddReport="Adicionar relatório"' + #13 +
  'sdxAddressCaption="Endereço"' + #13 +
  'sdxAdjustOnScale="&Ajuste de Escala"' + #13 +
  'sdxAdjustTo="&Para ajustar"' + #13 +
  'sdxAdministration="Administração"' + #13 +
  'sdxAggregatedLinks="Agregados Links:"' + #13 +
  'sdxAlignment="Alinhamento"' + #13 +
  'sdxAllDayMessage="todos os dias"' + #13 +
  'sdxAllRecords="Todos os registros"' + #13 +
  'sdxAncestorError="Encaixe e operações escondendo automática não estão disponíveis para controles declarados em um formulário ancestral."' + #13 +
  'sdxAppearance="Aparência"' + #13 +
  'sdxApril="Abril"' + #13 +
  'sdxAprilShort="Abril"' + #13 +
  'sdxAugust="Agosto"' + #13 +
  'sdxAugustShort="Agosto"' + #13 +
  'sdxAutoCalcPreviewLineCount="A&uto Calcular Preview Lines"' + #13 +
  'sdxAutoColumnsExpand="A&uto expandir Colunas"' + #13 +
  'sdxAutoNodesExpand="A&uto Expanda os nós"' + #13 +
  'sdxAutoRowsExpand="Auto &Linhas expandir"' + #13 +
  'sdxAutoTextDialogCaption="Editar entradas de AutoTexto"' + #13 +
  'sdxAutoWidth="Auto &Largura"' + #13 +
  'sdxAvailableItems="Itens disponíveis"' + #13 +
  'sdxAvailableLinks="&Disponível Links"' + #13 +
  'sdxAvailableReportLinks="Disponível ReportLinks"' + #13 +
  'sdxAvailableSources="&Disponível Fonte(s)"' + #13 +
  'sdxBackground="&Fundo"' + #13 +
  'sdxBadDatePrintRange="A data na caixa de fim não pode ser anterior à data na caixa Início."' + #13 +
  'sdxBadTimePrintRange="A hora de imprimir não são válidos. O horário de início deve preceder o tempo do fim."' + #13 +
  'sdxBandFont="Band Fonte"' + #13 +
  'sdxBands="&Bandas"' + #13 +
  'sdxBandsOnEveryPage="Bandas"' + #13 +
  'sdxBaseStyle="Base Estilo"' + #13 +
  'sdxBehaviors="Comportamentos"' + #13 +
  'sdxBehaviorsTab="Comportamentos"' + #13 +
  'sdxBestFit="&Melhor Ajuste"' + #13 +
  'sdxBorderColor="&Cor da Borda:"' + #13 +
  'sdxBorderLines="&borda"' + #13 +
  'sdxBorders="Bordas"' + #13 +
  'sdxBottom="&Fundo:"' + #13 +
  'sdxBottomMargin="Margem inferior"' + #13 +
  'sdxBrushColor="Escova de cor"' + #13 +
  'sdxBrushDlgCaption="Propriedades da Escova"' + #13 +
  'sdxBtnAddComposition="Add &Composição"' + #13 +
  'sdxBtnApply="&Aplicar"' + #13 +
  'sdxBtnAutomatic="&Automático"' + #13 +
  'sdxBtnBackground="segundo plano"' + #13 +
  'sdxBtnBrowse="&Navegue..."' + #13 +
  'sdxBtnCancel="Cancelar"' + #13 +
  'sdxBtnChangeFont="Alterar Fo&nte..."' + #13 +
  'sdxBtnClose="Fechar"' + #13 +
  'sdxBtnCopy="&Copiar..."' + #13 +
  'sdxBtnDefault="&Padrão..."' + #13 +
  'sdxBtnDefinePrintStyles="&Definir Estilos..."' + #13 +
  'sdxBtnDelete="&Deletar..."' + #13 +
  'sdxBtnDescription="&Descrição ..."' + #13 +
  'sdxBtnEdit="&Editar..."' + #13 +
  'sdxBtnEvenFont="igualar Fonte..."' + #13 +
  'sdxBtnFillEffects="&Efeitos de Preenchimento..."' + #13 +
  'sdxBtnFix="&fixar"' + #13 +
  'sdxBtnFixedFont="Fonte Fixa ..."' + #13 +
  'sdxBtnFont="Fo&nte..."' + #13 +
  'sdxBtnGroupFont="Gru&po Fonte ..."' + #13 +
  'sdxBtnHeaderBackground="&segundo plano"' + #13 +
  'sdxBtnHeadersFont="&Fonte cabeçalhos ..."' + #13 +
  'sdxBtnHelp="&Ajuda"' + #13 +
  'sdxBtnIgnore="&Ignorar"' + #13 +
  'sdxBtnInvertColors="I&nverter Cores"' + #13 +
  'sdxBtnMoreColors="&Mais Cores ..."' + #13 +
  'sdxBtnMoveDown="Descer"' + #13 +
  'sdxBtnMoveUp="Subir"' + #13 +
  'sdxBtnNew="&Novo..."' + #13 +
  'sdxBtnNoFill="&sem preenchimento"' + #13 +
  'sdxBtnNone="&Nenhum"' + #13 +
  'sdxBtnOptions="&Opções ..."' + #13 +
  'sdxBtnOtherTexture="Outra Te&xtura..."' + #13 +
  'sdxBtnPageSetup="Pa&gina Configuração..."' + #13 +
  'sdxBtnPrint="Imprimir ..."' + #13 +
  'sdxBtnPrintPreview="Imprimir Pre&view..."' + #13 +
  'sdxBtnPrintStyles="Estilos de Impressão"' + #13 +
  'sdxBtnProperties="P&ropriedades..."' + #13 +
  'sdxBtnRemoveInconsistents="Remove desnecessários"' + #13 +
  'sdxBtnRename="&Renomear..."' + #13 +
  'sdxBtnRestoreDefaults="&Restaurar Padrões"' + #13 +
  'sdxBtnRestoreOriginal="restaurar &Original"' + #13 +
  'sdxBtnSaveAs="Savar &Como..."' + #13 +
  'sdxBtnSelectPicture="Se&leciona Figura..."' + #13 +
  'sdxBtnShowToolBar="Mostrar&ToolBar"' + #13 +
  'sdxBtnStyleOptions="Opções de Estilo ..."' + #13 +
  'sdxBtnTexture="&Textura..."' + #13 +
  'sdxBtnTextureClear="Limpar"' + #13 +
  'sdxBtnTitleProperties="Título Propriedades ..."' + #13 +
  'sdxBtnYes="&Sim"' + #13 +
  'sdxBtnYesToAll="Sim para &Todos"' + #13 +
  'sdxBuildingReport="Construindo o relatório: Completo %d%%"' + #13 +
  'sdxBuildingReportStatusText="Construindo o relatório - Pressione Esc para cancelar"' + #13 +
  'sdxButtons="Botões"' + #13 +
  'sdxByBands="Por Bandas"' + #13 +
  'sdxByColumns="Por Colunas"' + #13 +
  'sdxByRows="Por &Linhas"' + #13 +
  'sdxByTopLevelGroups="Por grupos Nível Superior"' + #13 +
  'sdxCancel="Cancelar"' + #13 +
  'sdxCannotLoadImage="Não pode Carregar Imagem "%s""' + #13 +
  'sdxCannotPrintNoItemsAvailable="Não há itens disponíveis dentro do intervalo de impressão especificado."' + #13 +
  'sdxCannotPrintNoSelectedItems="Não é possível imprimir a não ser um item é selecionado. Selecione um item e tente imprimir novamente."' + #13 +
  'sdxCannotRenameFolderText="Não é possível renomear a pasta "%s". Uma pasta com o nome "%s" já existe. Especifique um nome diferente."' + #13 +
  'sdxCannotRenameItemText="Não é possível renomear item "%s". Um item com o nome "%s" já existe. Especifique um nome diferente."' + #13 +
  'sdxCannotUseOnEveryPageMode="Não é possível usar OnEveryPage Mode \n \nVocê deve ou (e) \n - Fechar todos os registros mestre \n - Alternar "desfazer Opção" off on "Comportamentos" Tab"' + #13 +
  'sdxCannotUseOnEveryPageModeInAggregatedState="Não é possível usar OnEveryPage Mode \nDurante o desempenho de agregados Estado"' + #13 +
  'sdxCaption="&título:"' + #13 +
  'sdxCaptionColor="Cor de títulor:"' + #13 +
  'sdxCaptionNodeFont="Nível  título Fonte"' + #13 +
  'sdxCaptionStyle="Título"' + #13 +
  'sdxCaptionTransparent="Título transparente"' + #13 +
  'sdxCardCaptionRowStyle="Cartão título linha"' + #13 +
  'sdxCardRowCaptionStyle="Cartão linha título"' + #13 +
  'sdxCardsRows="&Cartões"' + #13 +
  'sdxCardsTab="Cartões"' + #13 +
  'sdxCarLevelCaption="Carros"' + #13 +
  'sdxCarManufacturer="Fabricante"' + #13 +
  'sdxCarManufacturerCountry1="Alemanha"' + #13 +
  'sdxCarManufacturerCountry2="Estados Unidos"' + #13 +
  'sdxCarManufacturerCountry3="Alemanha"' + #13 +
  'sdxCarManufacturerCountry4="Reino Unido"' + #13 +
  'sdxCarManufacturerCountry5="Alemanha"' + #13 +
  'sdxCarModelColumnCaption="Modelo"' + #13 +
  'sdxCarName="Nome de carro"' + #13 +
  'sdxCarPhotoColumnCaption="Foto"' + #13 +
  'sdxCarTires="Pneus"' + #13 +
  'sdxCarTransmission="transmissão"' + #13 +
  'sdxCashCaption="dinheiro"' + #13 +
  'sdxCategoryStyle="Categoria"' + #13 +
  'sdxCenterOnPage="Centro, na página"' + #13 +
  'sdxCharts="Gráficos"' + #13 +
  'sdxCheckAll="Check &Todos"' + #13 +
  'sdxCheckAllChildren="Check Todos &Filhos"' + #13 +
  'sdxCheckMarks="Check Marcas"' + #13 +
  'sdxCheckMarksAsText="&Display Checkmarks como Texto"' + #13 +
  'sdxCircle="círculo"' + #13 +
  'sdxCloneStyleCaptionPrefix="Copiar (%d) de "' + #13 +
  'sdxCloseExplorerHint="Feche o Explorer"' + #13 +
  'sdxColumnFields="&Campos de Coluna"' + #13 +
  'sdxColumnHeaders="&Cabeçalhos de Coluna"' + #13 +
  'sdxColumnHeadersOnEveryPage="Coluna &Cabeçalhos"' + #13 +
  'sdxCompanyCaption="Companhia"' + #13 +
  'sdxCompanyName="Nome de Empresa"' + #13 +
  'sdxComponentAlreadyExists="Componente denominado "%s" já existe"' + #13 +
  'sdxComponentNotAssigned="%s \nNão designado "Componente de propriedade""' + #13 +
  'sdxComponentNotSupported="Componente "%s" não é suportado pelo TdxComponentPrinter"' + #13 +
  'sdxComponentNotSupportedByLink="Componente "%s" não é suportado pelo TdxComponentPrinter"' + #13 +
  'sdxComposition="Composição"' + #13 +
  'sdxCompositionDesignerCaption="Composição Editor"' + #13 +
  'sdxConfirmDeleteItem="Você deseja excluir os itens próximos %s ?"' + #13 +
  'sdxConfirmOverWrite="Arquivo "%s" já existe. sobrescrever?"' + #13 +
  'sdxConsumeSelectionStyle="Consumir estilo Seleção"' + #13 +
  'sdxContentEvenStyle="Mesmo conteúdo Linhas"' + #13 +
  'sdxContentOddStyle="Conteúdo Linhas ímpares"' + #13 +
  'sdxContentStyle="Conteúdo"' + #13 +
  'sdxContinuedMessage="Continuação"' + #13 +
  'sdxControls="&Controles"' + #13 +
  'sdxControlsPlace="Controles local"' + #13 +
  'sdxControlsTab="Controles"' + #13 +
  'sdxCopy="&Copiar"' + #13 +
  'sdxCopyOfItem="Cópia de"' + #13 +
  'sdxCountCaption="contar"' + #13 +
  'sdxCountIs="Contagem é: %d"' + #13 +
  'sdxCreatedBy="Criado de "' + #13 +
  'sdxCreatedOn="Criado Em"' + #13 +
  'sdxCurrentRecord="Atual \nregistro"' + #13 +
  'sdxCustom="personalizado"' + #13 +
  'sdxCustomSize="Tamanho personalizado"' + #13 +
  'sdxCyclicIDReferences="Referências Cyclic ID %s e %s"' + #13 +
  'sdxDataFields="&Campos de Dados"' + #13 +
  'sdxDataLoadErrorText="Não é possível carregar dados de relatório"' + #13 +
  'sdxDataProviderDontPresent="Não há nenhuma ligação com Assigned Componente de Composição"' + #13 +
  'sdxDataToPrintDoesNotExist="Não é possível ativar ReportLink porque PrintingSystem não encontrou nada para imprimir."' + #13 +
  'sdxDay="Dia"' + #13 +
  'sdxDBBasedExplorerItemDataLoadError="Não é possível carregar dados do relatório. \nOs dados estão corrompidos ou são bloqueados"' + #13 +
  'sdxDecember="Dezembro"' + #13 +
  'sdxDecemberShort="Dezembro"' + #13 +
  'sdxDefaultTray="Bandeja padrão"' + #13 +
  'sdxDefinePrintStylesCaption="Definir estilos de impressão"' + #13 +
  'sdxDefinePrintStylesMenuItem="Definir Print &Estilos ..."' + #13 +
  'sdxDefinePrintStylesTitle="Imprimir&Estilos:"' + #13 +
  'sdxDefinePrintStylesWarningClear="Você quer apagar todos os não-construída em estilos?"' + #13 +
  'sdxDefinePrintStylesWarningDelete="Você quer apagar "%s" ?"' + #13 +
  'sdxDeleteFolderMessageText="Excluir pasta "%s" ?"' + #13 +
  'sdxDeleteItemMessageText="Excluir Item "%s" ?"' + #13 +
  'sdxDeleteNonEmptyFolderMessageText="Pasta "%s" não está vazia. Delete de qualquer maneira?"' + #13 +
  'sdxDescription="&Descrição:"' + #13 +
  'sdxDetails="&Detalhes"' + #13 +
  'sdxDisplayGraphicsAsText="O display gráfico Como &Texto"' + #13 +
  'sdxDoubleLineEdgePattern="dobro linha"' + #13 +
  'sdxDownThenOver="&Abaixo, em seguida, sobre"' + #13 +
  'sdxDrawBorder="&Draw borda"' + #13 +
  'sdxDrawMode="Draw &Modo:"' + #13 +
  'sdxDrawModeBorrow="Emprestar da Fonte"' + #13 +
  'sdxDrawModeChess="Modo de Xadrez"' + #13 +
  'sdxDrawModeOddEven="Odd/ Mesmo Linhas Modo"' + #13 +
  'sdxDrawModeStrict="estrito"' + #13 +
  'sdxDTFormatsAutoUpdate="&Atualizar automaticamente"' + #13 +
  'sdxDTFormatsAvailableDateFormats="&Livre Formatos de Data:"' + #13 +
  'sdxDTFormatsAvailableTimeFormats="Disponível&Formato Hora:"' + #13 +
  'sdxDTFormatsCaption="Data e Hora"' + #13 +
  'sdxDTFormatsChangeDefaultFormat="Você quer mudar a data ea hora padrão formatos para corresponder "%s"  - "%s" ?"' + #13 +
  'sdxEast="Médio"' + #13 +
  'sdxEditDescription="Editar Descrição"' + #13 +
  'sdxEditReports="Editar relatórios"' + #13 +
  'sdxInternalErrorAutoHide="Erro interno enquanto os controles autohide."' + #13 +
  'sdxInternalErrorCreateLayout="Erro interno ao criar um %s object layout."' + #13 +
  'sdxInternalErrorDestroyLayout="Erro interno ao destruir um layout %s objeto."' + #13 +
  'sdxInternalErrorLayout="Erro interno no layout %s objeto."' + #13 +
  'sdxInternalErrorPainter="Erro interno no pintor TdxCustomDockControl."' + #13 +
  'sdxInvaldZoneOwner="Você não pode criar um TdxZone sem possuir TdxCustomDockControl."' + #13 +
  'sdxInvalidDockSiteParent="O pai dos TdxDockSite não pode ser TdxCustomDockControl."' + #13 +
  'sdxInvalidFloatingDeleting="Você não pode excluir um TdxCustomDockSite em modo de flutuação."' + #13 +
  'sdxInvalidFloatSiteDeleting="Você não pode excluir um TdxFloatDockSite."' + #13 +
  'sdxInvalidFloatSiteParent="O pai dos TdxFloatDockSite só pode ser TdxFloatForm."' + #13 +
  'sdxInvalidLayoutSiteDeleting="Você não pode excluir um TdxLayoutDockSite."' + #13 +
  'sdxInvalidOwner="O Dono do TdxCustomDockControl deve ser TCustomForm."' + #13 +
  'sdxInvalidPanelChild="Você não pode inserir um TdxCustomDockControl em TdxDockPanel (%s está sendo inserido)."' + #13 +
  'sdxInvalidParent="O pai do% s deve ser TdxCustomDockControl."' + #13 +
  'sdxInvalidParentAssigning="Você não pode definir o pai para este componente."' + #13 +
  'sdxInvalidSiteChild="Você só pode inserir um TdxCustomDockControl em TdxCustomDockSite (%s está sendo inserido)."' + #13 +
  'sdxManagerError="Você não pode ter mais de uma instância TdxDockingManager em um formulário."' + #13 +
  'secxAllDay="Todos os Dias"' + #13 +
  'secxAlldayevent="Todo Evento do Dia \n"' + #13 +
  'secxCategories="Categoria"' + #13 +
  'secxDescription="Descrição"' + #13 +
  'secxEndDate="DataFim"' + #13 +
  'secxEndTime="HoraFim"' + #13 +
  'secxExportStorageInvalid="Armazenamento não atribuídos"' + #13 +
  'secxFalse="FALSO"' + #13 +
  'secxFinish="Concluir"' + #13 +
  'secxLocation="Local"' + #13 +
  'secxNo="Não"' + #13 +
  'secxReminder=""' + #13 +
  'secxReminderDate="LembreteData"' + #13 +
  'secxReminderonoff="Lembreteonoff"' + #13 +
  'secxReminderTime="LembreteTempo"' + #13 +
  'secxSetDateRangeAnd="E"' + #13 +
  'secxSetDateRangeCaption="Definir Período"' + #13 +
  'secxSetDateRangeText="Exportação e criar ocorrências individuais de compromissos ou tarefas que ocorrem entre:"' + #13 +
  'secxShowtimeas="Mostrarhorario"' + #13 +
  'secxStart="Inicio"' + #13 +
  'secxStartDate="DataInicio"' + #13 +
  'secxStartTime="Tempo do Inicio"' + #13 +
  'secxState="Status"' + #13 +
  'secxSubject="Assunto"' + #13 +
  'secxTrue="Verdadeiro"' + #13 +
  'secxYes="Sim"';

  lMemoryStream := TMemoryStream.Create;
  Lista.SaveToStream(lMemoryStream);
  lMemoryStream.Position := 0;
  LoadFromStream(lMemoryStream);
  languageIndex := 1;
  Active := True;
end;


end.
