CREATE TABLE `mensagem` (
	`COD_MENSAGEM` INT(11) NOT NULL AUTO_INCREMENT,
	`CONTATO` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`TELEFONE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`MENSAGEM` VARCHAR(10000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`DATA_HORA_CRIACAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`ATIVO` TINYINT(1) NULL DEFAULT NULL,
	`IDCONVERSA` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`TIPO_MENSAGEM` CHAR(1) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`DATA_ENVIO_RECEBIDO` TIMESTAMP NULL DEFAULT NULL,
	`ARQUIVO` BLOB NULL DEFAULT NULL,
	`DATA_PROCESSADO_API` TIMESTAMP NULL DEFAULT NULL,
	`STATUS` CHAR(2) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`COD_MENSAGEM`) USING BTREE,
	INDEX `TELEFONE` (`TELEFONE`),
	INDEX `MENSAGEM` (`MENSAGEM`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=60
;
